import { inferSubtitleTracks, mediaSource } from '../lib/media'
import type { HeroineId, RouteId, StatId, StoryScene } from './types'

function stage(
  label: string,
  motif: string,
  quote: string,
  palette: string,
  glow: string,
  haze: string,
  ...media: string[]
) {
  const sources = media.map((source) => mediaSource(source))

  return {
    label,
    motif,
    quote,
    palette,
    glow,
    haze,
    media: sources,
    subtitles: inferSubtitleTracks(sources),
  }
}

export const statLabels: Record<StatId, string> = {
  courage: '胆识',
  wit: '机辨',
  mercy: '仁心',
  spirit: '灵识',
}

export const routeLabels: Record<RouteId, string> = {
  common: '序章',
  xiaoqian: '聂小倩线',
  feili: '燕绯璃线',
  wange: '苏晚歌线',
  jianyue: '沈见月线',
  hidden: '回梦隐藏线',
}

export const routeAccent: Record<RouteId, string> = {
  common: '#d3ad68',
  xiaoqian: '#d7c8ff',
  feili: '#8ee2d2',
  wange: '#ffb476',
  jianyue: '#b8cafc',
  hidden: '#d6defa',
}

export const heroineShowcase: Record<
  HeroineId,
  {
    name: string
    title: string
    tagline: string
    blurb: string
    accent: string
  }
> = {
  xiaoqian: {
    name: '聂小倩',
    title: '纸伞渡魂',
    tagline: '她最怕被人记住，也最怕无人记住。',
    blurb: '主打共情与灵识。你要学会先听懂她，再想着救她。',
    accent: '#d7c8ff',
  },
  feili: {
    name: '燕绯璃',
    title: '焚符猎影',
    tagline: '剑与火都利落，犹豫反倒像她最少见的伤口。',
    blurb: '主打胆识与机辨。是并肩破局，不是替她抢局。',
    accent: '#8ee2d2',
  },
  wange: {
    name: '苏晚歌',
    title: '夜市掌灯',
    tagline: '她把人心当买卖，也偷偷把真心留在账外。',
    blurb: '主打仁心与机辨。你得先学会平等地和她谈条件。',
    accent: '#ffb476',
  },
  jianyue: {
    name: '沈见月',
    title: '城隍听审',
    tagline: '她看上去最稳，其实最想有人在风口时站近一点。',
    blurb: '主打胆识与仁心。重点不是破案，而是扛住破案之后的代价。',
    accent: '#b8cafc',
  },
}

export const routeOrder: HeroineId[] = ['xiaoqian', 'feili', 'wange', 'jianyue']

export const routeEntryScene: Record<RouteId, string> = {
  common: 'prologue-crossroads',
  xiaoqian: 'xiaoqian-rain-pavilion',
  feili: 'feili-tower-fire',
  wange: 'wange-lantern-market',
  jianyue: 'jianyue-bridge-docket',
  hidden: 'hidden-rewind-room',
}

export const radiantEndingIds: Record<HeroineId, string> = {
  xiaoqian: 'ending-xiaoqian-radiant',
  feili: 'ending-feili-radiant',
  wange: 'ending-wange-radiant',
  jianyue: 'ending-jianyue-radiant',
}

export const storyScenes: Record<string, StoryScene> = {
  'prologue-crossroads': {
    id: 'prologue-crossroads',
    route: 'common',
    act: '序章',
    title: '借火之夜',
    subtitle: '兰若镇四面都亮着不同的灯',
    speaker: '旁白',
    location: '兰若古镇口',
    time: '子时',
    mood: '风潮将至，所有命运都在等你先迈一步。',
    summary: [
      '你提着一盏快要熄灭的旧灯走进兰若。镇口没有人迎你，只有四处不同的亮色: 湖廊里有一把纸伞，塔楼上有焚符火光，夜市口有一串狐灯，城隍桥边则压着一沓未结的卷宗。',
      '从这一刻起，这个 Demo 不只是“选女主”的壳子，而是完整可扩展的互动影游数据结构。后续只要替换视频与文本，就能继续把体验做深。',
    ],
    choices: [
      {
        id: 'to-xiaoqian',
        label: '往湖廊走',
        caption: '那把纸伞像专门替你留了一半雨。',
        to: 'xiaoqian-rain-pavilion',
        statShift: { mercy: 1 },
        bondShift: { xiaoqian: 1 },
      },
      {
        id: 'to-feili',
        label: '上塔楼去',
        caption: '有人在风里烧符，像在跟夜色抢先手。',
        to: 'feili-tower-fire',
        statShift: { wit: 1 },
        bondShift: { feili: 1 },
      },
      {
        id: 'to-wange',
        label: '去夜市看灯',
        caption: '最热闹的地方，往往也最会藏秘密。',
        to: 'wange-lantern-market',
        statShift: { mercy: 1 },
        bondShift: { wange: 1 },
      },
      {
        id: 'to-jianyue',
        label: '走上城隍桥',
        caption: '有人把整个镇子的麻烦都压在卷宗下。',
        to: 'jianyue-bridge-docket',
        statShift: { courage: 1 },
        bondShift: { jianyue: 1 },
      },
    ],
    stage: stage(
      '序章舞台',
      '四灯并映',
      '真正改变故事的，常常只是第一个转身。',
      '#211913',
      '#d3ad68',
      '#7e6641',
      '/media/common/crossroads.mp4',
      '/media/common/crossroads.webm',
    ),
    isEnding: false,
  },
  'xiaoqian-rain-pavilion': {
    id: 'xiaoqian-rain-pavilion',
    route: 'xiaoqian',
    act: '第一幕',
    title: '伞下借月',
    subtitle: '她站在雨里，却像早就知道你会来',
    speaker: '聂小倩',
    location: '湖心长廊',
    time: '子时三刻',
    mood: '白雨细密，人的心反而容易被听见。',
    summary: [
      '雨丝从檐角垂下来，她把纸伞分给你半边，却始终不肯让你看清她完整的影子。她说兰若镇今晚会少一个名字，如果你现在回头，还能装作没听见。',
      '小倩线的核心不在“降妖”而在“赎名”。很多正确答案都不会来得很快。',
    ],
    choices: [
      {
        id: 'share-lantern',
        label: '把灯递给她',
        caption: '先让她暖一暖，再问她是不是鬼。',
        to: 'xiaoqian-bone-zither',
        statShift: { mercy: 1 },
        bondShift: { xiaoqian: 1 },
      },
      {
        id: 'question-shadow',
        label: '问她为何没有影子',
        caption: '你不想让自己被柔声细雨骗过去。',
        to: 'xiaoqian-bone-zither',
        statShift: { wit: 1 },
      },
    ],
    stage: stage(
      '小倩初遇',
      '纸伞与水纹',
      '若你愿意慢一点，很多鬼话也会变成人话。',
      '#1b1730',
      '#d7c8ff',
      '#6d5c96',
      '/media/xiaoqian/rain-pavilion.mp4',
      '/media/xiaoqian/rain-pavilion.webm',
    ),
    isEnding: false,
  },
  'xiaoqian-bone-zither': {
    id: 'xiaoqian-bone-zither',
    route: 'xiaoqian',
    act: '第二幕',
    title: '骨琴旧契',
    subtitle: '她把最难听的话亲口说给你',
    speaker: '聂小倩',
    location: '废戏台下',
    time: '丑时',
    mood: '戏台空着，却像还有谁等着听收场。',
    summary: [
      '戏台底下藏着一把骨琴和一页旧契，小倩终于承认自己是被买断姓名的孤魂。她说自己不怕散，只怕在散之前再被人拿去换一次价钱。',
      '如果你只想“赢一场”，这条线会立刻变得很残忍；如果你愿意陪她把名字找回来，它也会比看上去柔软。',
    ],
    choices: [
      {
        id: 'tune-zither',
        label: '陪她把骨琴调回人音',
        caption: '先把她的名字从旧契里分出来。',
        to: 'xiaoqian-ferry-gate',
        statShift: { spirit: 1 },
        bondShift: { xiaoqian: 1 },
      },
      {
        id: 'tear-contract',
        label: '当场撕契',
        caption: '你不愿再看任何东西困住她。',
        to: 'xiaoqian-ferry-gate',
        statShift: { courage: 1 },
        bondShift: { xiaoqian: -1 },
      },
    ],
    stage: stage(
      '骨琴戏台',
      '残幕与旧纸',
      '救一个人，有时要比斩一只妖更会忍。',
      '#1a1226',
      '#ecdfff',
      '#8a6baf',
      '/media/xiaoqian/bone-zither.mp4',
      '/media/xiaoqian/bone-zither.webm',
    ),
    isEnding: false,
  },
  'xiaoqian-ferry-gate': {
    id: 'xiaoqian-ferry-gate',
    route: 'xiaoqian',
    act: '第三幕',
    title: '渡口开伞',
    subtitle: '天快亮了，你只够做一次真正的决定',
    speaker: '旁白',
    location: '忘川渡口',
    time: '寅时',
    mood: '所有雾都在问你: 想赢，还是想带她活着过去。',
    summary: [
      '渡口的雾门正在张开，门后是她可能重新为人的路，也是你最后一次替她做决定的机会。小倩没再躲你的视线，只轻声说，不要替她挑一个漂亮的死法。',
    ],
    choices: [
      {
        id: 'return-her-name',
        label: '把名字还给她',
        caption: '要求灵识 3 / 仁心 3 / 小倩羁绊 3。',
        to: 'ending-xiaoqian-radiant',
        lock: {
          stats: { spirit: 3, mercy: 3 },
          bonds: { xiaoqian: 3 },
          reason: '你还没把她真正当作一个“想继续活的人”来爱。',
        },
      },
      {
        id: 'break-fog-gate',
        label: '强破雾门',
        caption: '你或许能赢过黑夜，却未必赢回她。',
        to: 'ending-xiaoqian-fracture',
      },
    ],
    stage: stage(
      '渡口终局',
      '长风开伞',
      '真正能把她带出去的，不是力气，而是你肯不肯把选择还给她。',
      '#1f1730',
      '#d9c8fb',
      '#786191',
      '/media/xiaoqian/ferry-gate.mp4',
      '/media/xiaoqian/ferry-gate.webm',
    ),
    isEnding: false,
  },
  'ending-xiaoqian-radiant': {
    id: 'ending-xiaoqian-radiant',
    route: 'xiaoqian',
    act: '结局',
    title: '人间有名',
    subtitle: '她终于不用再借别人的影子过河',
    speaker: '聂小倩',
    location: '晨雾之外',
    time: '卯时',
    mood: '天光很轻，刚好够照清两个人。',
    summary: [
      '雾门没有碎，而是慢慢让开。小倩踩过水面时第一次有了完整的影子，也第一次可以把自己的名字完整地说给你听。她没有谢你，只轻轻笑，说以后若还有人问兰若夜里最亮的是什么，就说是有人认真听完了她。',
    ],
    choices: [],
    stage: stage(
      '小倩好结局',
      '晨雾收束',
      '记住她，不是把她留下，而是让她终于能去向自己想去的地方。',
      '#231a2f',
      '#efe2ff',
      '#8f74af',
      '/media/xiaoqian/ending-radiant.mp4',
      '/media/xiaoqian/ending-radiant.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-xiaoqian-radiant',
      name: '聂小倩·人间有名',
      tone: 'radiant',
      relic: '半面纸伞',
      summary: '你没有抢她的人生，而是把选择的权利还给了她。',
    },
  },
  'ending-xiaoqian-fracture': {
    id: 'ending-xiaoqian-fracture',
    route: 'xiaoqian',
    act: '结局',
    title: '雾里失声',
    subtitle: '门碎了，名字也跟着散了',
    speaker: '旁白',
    location: '渡口风口',
    time: '卯时',
    mood: '夜被你打穿了，但天没有为谁亮起来。',
    summary: [
      '你一剑斩开雾门时，小倩也跟着那页旧契一同散进风里。你把她从怪物手里抢出来，却没来得及把她从“被决定”的命里抢出来。回到镇口时，你已经记不清她声音的尾音。',
    ],
    choices: [],
    stage: stage(
      '小倩坏结局',
      '裂伞与残雾',
      '最难受的输法，是你明明赢了，却没能把她带回来。',
      '#18111f',
      '#b9a1d6',
      '#5c456e',
      '/media/xiaoqian/ending-fracture.mp4',
      '/media/xiaoqian/ending-fracture.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-xiaoqian-fracture',
      name: '聂小倩·雾里失声',
      tone: 'fracture',
      relic: '断骨琴弦',
      summary: '你把夜斩碎了，却也把她最后的退路一并斩碎。',
    },
  },
  'feili-tower-fire': {
    id: 'feili-tower-fire',
    route: 'feili',
    act: '第一幕',
    title: '塔楼焚符',
    subtitle: '她的火先照到妖，再照到你',
    speaker: '燕绯璃',
    location: '镇北塔楼',
    time: '子时三刻',
    mood: '塔楼风硬，像每一句话都该直着说。',
    summary: [
      '绯璃站在塔楼边缘烧符，火星一路压着夜色往下落。她见你上来，只把一张新画的镇符塞进你手里，说楼下混进来的不是妖，是被妖借走心窍的人。',
      '这条线最怕的不是危险，而是你只顾替她冲，而没学会和她一起判断。',
    ],
    choices: [
      {
        id: 'map-the-array',
        label: '替她重画阵图',
        caption: '先把局看明白，才知道该往哪一步狠。',
        to: 'feili-ash-courtyard',
        statShift: { wit: 1 },
        bondShift: { feili: 1 },
      },
      {
        id: 'take-the-front',
        label: '接过火符守正面',
        caption: '你想让她腾出手来喘一口气。',
        to: 'feili-ash-courtyard',
        statShift: { courage: 1 },
        bondShift: { feili: 1 },
      },
    ],
    stage: stage(
      '绯璃初遇',
      '高塔与焚符',
      '她不是不需要帮忙，只是不习惯有人站得住。',
      '#102322',
      '#8ee2d2',
      '#366f66',
      '/media/feili/tower-fire.mp4',
      '/media/feili/tower-fire.webm',
    ),
    isEnding: false,
  },
  'feili-ash-courtyard': {
    id: 'feili-ash-courtyard',
    route: 'feili',
    act: '第二幕',
    title: '灰庭问剑',
    subtitle: '她终于把真正犹豫的事说出口',
    speaker: '燕绯璃',
    location: '封灰庭',
    time: '丑时',
    mood: '火焰烧得越直，人的犹豫就越明显。',
    summary: [
      '你们在封灰庭找到真正的妖核，绯璃却没有立刻下手。她说一旦今天焚尽，镇上某个被附身的人也会一起没命。她刀快，可她最讨厌拿“效率”替别人决定值不值得被救。',
    ],
    choices: [
      {
        id: 'save-host',
        label: '陪她拆核救人',
        caption: '慢一点，但把人命也算进去。',
        to: 'feili-blaze-seal',
        statShift: { mercy: 1 },
        bondShift: { feili: 1 },
      },
      {
        id: 'force-burn',
        label: '劝她立刻焚尽',
        caption: '你担心拖下去会失去更多。',
        to: 'feili-blaze-seal',
        statShift: { courage: 1 },
        bondShift: { feili: -1 },
      },
    ],
    stage: stage(
      '灰庭逼问',
      '火纹与灰池',
      '并肩不是帮她更快地下手，而是在她犹豫时也不松开。',
      '#10221f',
      '#b8fff1',
      '#4d8379',
      '/media/feili/ash-courtyard.mp4',
      '/media/feili/ash-courtyard.webm',
    ),
    isEnding: false,
  },
  'feili-blaze-seal': {
    id: 'feili-blaze-seal',
    route: 'feili',
    act: '第三幕',
    title: '焰印收官',
    subtitle: '最后一道火，不该只烧在妖身上',
    speaker: '旁白',
    location: '封印井口',
    time: '寅时',
    mood: '要结束这一夜，你们得先决定成为什么样的人。',
    summary: [
      '封印井口只剩最后一道焰印，绯璃问你要不要把事情真相一并公之于众。那会让她背上失控之责，却也能替被附身的人洗掉污名；若你们只求安稳，这些话永远都可以不说。',
    ],
    choices: [
      {
        id: 'name-the-truth',
        label: '和她一起把真相摊到天亮',
        caption: '要求胆识 3 / 机辨 3 / 绯璃羁绊 3。',
        to: 'ending-feili-radiant',
        lock: {
          stats: { courage: 3, wit: 3 },
          bonds: { feili: 3 },
          reason: '你还没有足够的判断与信任，去陪她承担“说出真相”的后果。',
        },
      },
      {
        id: 'leave-it-buried',
        label: '烧净现场，只求平稳收场',
        caption: '镇子会安静下来，你们也会一起错过些什么。',
        to: 'ending-feili-fracture',
      },
    ],
    stage: stage(
      '绯璃终局',
      '封井火纹',
      '对她来说，真正难的不是斩妖，而是决定要不要把自己一起放上火里。',
      '#122520',
      '#8ee2d2',
      '#3b7268',
      '/media/feili/blaze-seal.mp4',
      '/media/feili/blaze-seal.webm',
    ),
    isEnding: false,
  },
  'ending-feili-radiant': {
    id: 'ending-feili-radiant',
    route: 'feili',
    act: '结局',
    title: '火照长明',
    subtitle: '她终于不是独自背着光的人',
    speaker: '燕绯璃',
    location: '塔楼天台',
    time: '卯时',
    mood: '风还是大，但这次有人和她一起站着。',
    summary: [
      '天亮时，绯璃把最后一张焚符压在栏杆上，没有再藏起自己的名字。她说以前总觉得站得越前就越安全，现在倒明白了，安全不是没人靠近，而是有人靠近之后你也不必先把刀举起来。',
    ],
    choices: [],
    stage: stage(
      '绯璃好结局',
      '晨火与高塔',
      '她愿意把后背交给你，不是因为你替她赢，而是因为你肯和她一起承担。',
      '#13221d',
      '#c8fff6',
      '#579184',
      '/media/feili/ending-radiant.mp4',
      '/media/feili/ending-radiant.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-feili-radiant',
      name: '燕绯璃·火照长明',
      tone: 'radiant',
      relic: '焚符短刃',
      summary: '你没有替她抢过所有战斗，而是在最重要的一次选择里和她站成了并肩。',
    },
  },
  'ending-feili-fracture': {
    id: 'ending-feili-fracture',
    route: 'feili',
    act: '结局',
    title: '灰落无声',
    subtitle: '镇子安静了，她也跟着沉默了',
    speaker: '旁白',
    location: '塔楼背风面',
    time: '卯时',
    mood: '一切都收得太快，于是很多话也再没机会说。',
    summary: [
      '你们把现场烧得很干净，干净到连真相都不剩。绯璃没有责怪你，只把佩刀重新系好，像在把自己又收回那个谁都进不来的壳里。她仍会记得你，但不会再愿意把犹豫交给你看。',
    ],
    choices: [],
    stage: stage(
      '绯璃坏结局',
      '冷灰回落',
      '有些“安稳”只是把最该说的话一起埋掉。',
      '#0d1916',
      '#5fa396',
      '#2e4e47',
      '/media/feili/ending-fracture.mp4',
      '/media/feili/ending-fracture.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-feili-fracture',
      name: '燕绯璃·灰落无声',
      tone: 'fracture',
      relic: '残烧镇符',
      summary: '你把局收住了，却也把她最珍贵的一点信任烧回了灰里。',
    },
  },
  'wange-lantern-market': {
    id: 'wange-lantern-market',
    route: 'wange',
    act: '第一幕',
    title: '千灯夜价',
    subtitle: '她笑着开价，也笑着试探你值几分真心',
    speaker: '苏晚歌',
    location: '狐灯夜市',
    time: '子时三刻',
    mood: '越热闹的地方，越需要有人真正看清谁在装糊涂。',
    summary: [
      '晚歌在灯市最高的摊位上卖愿望，也卖后悔。她看你第一眼就说，今晚所有东西都可以讲价，只有“陪我把这条街走完”不讲。你不知道她在玩笑，还是真的在挑人。',
    ],
    choices: [
      {
        id: 'inspect-ledger',
        label: '替她看账',
        caption: '先弄清楚这条街到底欠了她什么。',
        to: 'wange-red-ledger',
        statShift: { wit: 1 },
        bondShift: { wange: 1 },
      },
      {
        id: 'guard-the-stall',
        label: '替她看摊',
        caption: '让她先去把最难哄的那位客人送走。',
        to: 'wange-red-ledger',
        statShift: { mercy: 1 },
        bondShift: { wange: 1 },
      },
    ],
    stage: stage(
      '晚歌初遇',
      '狐灯与软纱',
      '她最会做买卖，也最会把真话夹在玩笑里。',
      '#29150e',
      '#ffb476',
      '#985022',
      '/media/wange/lantern-market.mp4',
      '/media/wange/lantern-market.webm',
    ),
    isEnding: false,
  },
  'wange-red-ledger': {
    id: 'wange-red-ledger',
    route: 'wange',
    act: '第二幕',
    title: '红账未平',
    subtitle: '她终于把那一页不肯给人看的账翻给你',
    speaker: '苏晚歌',
    location: '灯市高阁',
    time: '丑时',
    mood: '账越翻到后面，越不像在算钱。',
    summary: [
      '红账最后一页记的不是钱，是名字。晚歌承认自己当年为了活下来，签过一份把半个真名拿去典当的玉契。如今这条街每一盏灯都能替她赚钱，却没有哪一盏能替她把人心换回来。',
    ],
    choices: [
      {
        id: 'repay-the-street',
        label: '陪她先把欠街坊的还上',
        caption: '你想让她知道，真心也可以先记在账上。',
        to: 'wange-golden-ink',
        statShift: { mercy: 1 },
        bondShift: { wange: 1 },
      },
      {
        id: 'hunt-the-jade',
        label: '先追玉契下落',
        caption: '你想先切断控制她的人。',
        to: 'wange-golden-ink',
        statShift: { spirit: 1 },
      },
    ],
    stage: stage(
      '红账揭页',
      '灯影与金墨',
      '她嘴上最会算，心里最不会。',
      '#2a170f',
      '#ffcb96',
      '#9e5a2d',
      '/media/wange/red-ledger.mp4',
      '/media/wange/red-ledger.webm',
    ),
    isEnding: false,
  },
  'wange-golden-ink': {
    id: 'wange-golden-ink',
    route: 'wange',
    act: '第三幕',
    title: '金墨落款',
    subtitle: '最后一笔，写的是交易还是承诺',
    speaker: '旁白',
    location: '夜市天台',
    time: '寅时',
    mood: '灯火翻滚，像整条街都在等她签自己的名字。',
    summary: [
      '玉契被送回来了，只剩最后一道落款。晚歌问你，要不要和她一起签一份新的平等约，让这条街以后赚的每一分都见光；或者干脆把玉契卖回去，换一个更轻松、也更体面的结局。',
    ],
    choices: [
      {
        id: 'sign-equal-vow',
        label: '签下平等新约',
        caption: '要求机辨 3 / 仁心 3 / 晚歌羁绊 3。',
        to: 'ending-wange-radiant',
        lock: {
          stats: { wit: 3, mercy: 3 },
          bonds: { wange: 3 },
          reason: '她现在仍觉得你更像精明的过客，而不是愿意和她并立的人。',
        },
      },
      {
        id: 'sell-the-jade-back',
        label: '把玉契卖回去',
        caption: '你能得到很多，却不一定还留下她。',
        to: 'ending-wange-fracture',
      },
    ],
    stage: stage(
      '晚歌终局',
      '金墨与风灯',
      '再漂亮的交易，也比不上她第一次愿意把真心写在明面上。',
      '#28160f',
      '#ffbc7c',
      '#8a461e',
      '/media/wange/golden-ink.mp4',
      '/media/wange/golden-ink.webm',
    ),
    isEnding: false,
  },
  'ending-wange-radiant': {
    id: 'ending-wange-radiant',
    route: 'wange',
    act: '结局',
    title: '同灯共账',
    subtitle: '她第一次笑得不像在讲价',
    speaker: '苏晚歌',
    location: '天台风灯阵',
    time: '卯时',
    mood: '风还在吹，账本却终于合上得很轻。',
    summary: [
      '晚歌把那本红账亲手扔进火盆，说从今以后她不再用自己去填平每一笔亏空。她朝你抬了抬下巴，像还是那副会开价的样子，却第一次把最珍贵的部分毫不遮掩地放到了明处。',
    ],
    choices: [],
    stage: stage(
      '晚歌好结局',
      '灯海收束',
      '她把名字写回自己手里，也把未来分给了你半页。',
      '#311b12',
      '#ffd2a4',
      '#a96131',
      '/media/wange/ending-radiant.mp4',
      '/media/wange/ending-radiant.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-wange-radiant',
      name: '苏晚歌·同灯共账',
      tone: 'radiant',
      relic: '鎏金账册',
      summary: '你没有把她当风险或奖赏，而是当作可以平等落款的人。',
    },
  },
  'ending-wange-fracture': {
    id: 'ending-wange-fracture',
    route: 'wange',
    act: '结局',
    title: '灯尽买卖',
    subtitle: '她仍会对你笑，只是不再对你认真',
    speaker: '旁白',
    location: '夜市尾巷',
    time: '卯时',
    mood: '热闹散了，只剩一盏做生意的灯还亮着。',
    summary: [
      '玉契成交时，晚歌替你挑了最好看的一盏灯。她照旧会说漂亮话，照旧会在你来时招呼你坐，却再也不会让你看见那本真正重要的账。你成了她最熟悉的客人，却永远不是归处。',
    ],
    choices: [],
    stage: stage(
      '晚歌坏结局',
      '残灯与空席',
      '有些失去不会吵闹，只会把你安安静静地放回“过客”的位置。',
      '#24120c',
      '#d38c4a',
      '#6f3718',
      '/media/wange/ending-fracture.mp4',
      '/media/wange/ending-fracture.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-wange-fracture',
      name: '苏晚歌·灯尽买卖',
      tone: 'fracture',
      relic: '空灯铜签',
      summary: '你得到了最轻松的答案，也把她最认真的一面亲手错过去了。',
    },
  },
  'jianyue-bridge-docket': {
    id: 'jianyue-bridge-docket',
    route: 'jianyue',
    act: '第一幕',
    title: '桥上听审',
    subtitle: '她把全城的风都压在卷宗上',
    speaker: '沈见月',
    location: '城隍桥',
    time: '子时三刻',
    mood: '人声都远，只有纸页翻动得格外清楚。',
    summary: [
      '见月守在城隍桥边对失踪案卷，她一句废话都没有，开口就问你敢不敢陪她查到天亮，因为这案子再拖一会儿，她自己就会先被推去顶罪。',
      '她看上去最像规则的一部分，其实最清楚规则什么时候会先伤人。',
    ],
    choices: [
      {
        id: 'sort-the-evidence',
        label: '帮她理卷宗',
        caption: '先把线索拼回成一张完整的网。',
        to: 'jianyue-echo-roof',
        statShift: { wit: 1 },
        bondShift: { jianyue: 1 },
      },
      {
        id: 'walk-the-streets',
        label: '陪她夜巡',
        caption: '比起线索，你更担心她一个人撑着太久。',
        to: 'jianyue-echo-roof',
        statShift: { courage: 1 },
        bondShift: { jianyue: 1 },
      },
    ],
    stage: stage(
      '见月初遇',
      '桥雾与卷宗',
      '她的稳不是不累，只是还没等到能一起累的人。',
      '#131a2c',
      '#b8cafc',
      '#5b6f9a',
      '/media/jianyue/bridge-docket.mp4',
      '/media/jianyue/bridge-docket.webm',
    ),
    isEnding: false,
  },
  'jianyue-echo-roof': {
    id: 'jianyue-echo-roof',
    route: 'jianyue',
    act: '第二幕',
    title: '瓦上回声',
    subtitle: '她第一次把“怕”这个字说给别人听',
    speaker: '沈见月',
    location: '县衙屋脊',
    time: '丑时',
    mood: '风越急，越能听出谁还肯留在身侧。',
    summary: [
      '真凶开始把流言和证据一起往她身上引。见月站在屋脊上盯着满城灯火，说自己不是怕丢官，而是怕所有替她作证的人都会被一起牵连。她说完这句才意识到，自己已经很久没把这种话说给别人听了。',
    ],
    choices: [
      {
        id: 'open-the-ledger',
        label: '主张公开账本',
        caption: '先把真相推到谁都藏不住的地方。',
        to: 'jianyue-court-sunrise',
        statShift: { wit: 1 },
        bondShift: { jianyue: 1 },
      },
      {
        id: 'shield-her-name',
        label: '先替她挡风',
        caption: '你宁可自己先挨那一轮逼问。',
        to: 'jianyue-court-sunrise',
        statShift: { mercy: 1 },
        bondShift: { jianyue: 1 },
      },
    ],
    stage: stage(
      '见月风口',
      '高檐与灯河',
      '她不是不肯示弱，只是很少真的等得到回应。',
      '#172133',
      '#d7e1ff',
      '#6980b0',
      '/media/jianyue/echo-roof.mp4',
      '/media/jianyue/echo-roof.webm',
    ),
    isEnding: false,
  },
  'jianyue-court-sunrise': {
    id: 'jianyue-court-sunrise',
    route: 'jianyue',
    act: '第三幕',
    title: '堂前迎光',
    subtitle: '要么并肩往前一步，要么看着她独自接下所有目光',
    speaker: '旁白',
    location: '县衙大堂',
    time: '寅时',
    mood: '所有视线都压下来时，你的沉默也会成为一种答案。',
    summary: [
      '堂上众口相逼，见月已经准备独自把所有责问接过去。她没有再向你求助，但你知道，有些人不是不需要依靠，只是从来没等到谁会真的走过去。',
    ],
    choices: [
      {
        id: 'step-into-the-light',
        label: '站到她身边',
        caption: '要求胆识 3 / 仁心 3 / 见月羁绊 3。',
        to: 'ending-jianyue-radiant',
        lock: {
          stats: { courage: 3, mercy: 3 },
          bonds: { jianyue: 3 },
          reason: '你还没有把“并肩承担后果”这件事做得足够坚定。',
        },
      },
      {
        id: 'watch-from-the-crowd',
        label: '让她自己顶住',
        caption: '案子也许还能赢，但你们之间就只剩距离。',
        to: 'ending-jianyue-fracture',
      },
    ],
    stage: stage(
      '见月终局',
      '长堂与晨光',
      '喜欢她，不是觉得她强，而是知道她再强也该有人并肩。',
      '#121a2b',
      '#b8cafc',
      '#667aa8',
      '/media/jianyue/court-sunrise.mp4',
      '/media/jianyue/court-sunrise.webm',
    ),
    isEnding: false,
  },
  'ending-jianyue-radiant': {
    id: 'ending-jianyue-radiant',
    route: 'jianyue',
    act: '结局',
    title: '同判天明',
    subtitle: '她终于不用一个人把所有声音都接住',
    speaker: '沈见月',
    location: '县衙长廊',
    time: '卯时',
    mood: '天亮得很慢，却终于没那么冷了。',
    summary: [
      '人群散去后，见月把那沓几乎一夜没离手的卷宗推给你半边，说以后若有人问起这一夜是谁把案子扛到天亮，名字别只写她一个。她看上去还是很稳，却第一次稳得像有人可以靠。',
    ],
    choices: [],
    stage: stage(
      '见月好结局',
      '卷宗与长廊',
      '她愿意把最重的那半摊给你，不是因为自己扛不动，而是终于愿意一起走。',
      '#152033',
      '#dce6ff',
      '#7b8eb8',
      '/media/jianyue/ending-radiant.mp4',
      '/media/jianyue/ending-radiant.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-jianyue-radiant',
      name: '沈见月·同判天明',
      tone: 'radiant',
      relic: '城隍铜印',
      summary: '你不仅信她会赢，也愿意陪她一起承担赢之前的全部风声。',
    },
  },
  'ending-jianyue-fracture': {
    id: 'ending-jianyue-fracture',
    route: 'jianyue',
    act: '结局',
    title: '人群之后',
    subtitle: '她还是赢了案，只是你们再没走到并肩的位置',
    speaker: '旁白',
    location: '堂外石阶',
    time: '卯时',
    mood: '风从长阶吹过去，像把一句没说出口的话吹散了。',
    summary: [
      '见月独自把所有攻讦都接完了。她仍然赢下案子，也仍然会在你看过来时点一下头，可那点温度已经只剩礼貌。你们之间只差那一步，却偏偏没有人在最该走过去的时候真正迈出脚。',
    ],
    choices: [],
    stage: stage(
      '见月坏结局',
      '空堂与石阶',
      '她最难的不是受伤，而是发现你最终也站回了人群。',
      '#0f1726',
      '#94a9da',
      '#4e5d80',
      '/media/jianyue/ending-fracture.mp4',
      '/media/jianyue/ending-fracture.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-jianyue-fracture',
      name: '沈见月·人群之后',
      tone: 'fracture',
      relic: '折角卷宗',
      summary: '你看见了她最难的时候，却没有在那一刻真正走进她的风口。',
    },
  },
  'hidden-rewind-room': {
    id: 'hidden-rewind-room',
    route: 'hidden',
    act: '回梦线',
    title: '回放室',
    subtitle: '至少拿到两个明亮结局后，故事才肯让你回头',
    speaker: '旁白',
    location: '戏楼放映间',
    time: '梦中',
    mood: '这一次，你不是重看片段，而是被片段重看。',
    summary: [
      '当你把至少两个人带到天亮之后，兰若的戏楼终于在梦里为你点灯。空放映间里悬着四件旧物: 纸伞、焚符短刃、鎏金账册、城隍铜印。它们都在提醒你，这部戏真正缺的从来不是结局，而是能不能把所有名字写回同一张片单。',
    ],
    choices: [
      {
        id: 'collect-the-reels',
        label: '把四件旧物一一归位',
        caption: '你决定继续记住她们，而不是只记住某一条赢法。',
        to: 'hidden-mirror-stage',
        statShift: { spirit: 1 },
      },
      {
        id: 'leave-the-room',
        label: '转身离开放映间',
        caption: '忘记会更轻，但也更空。',
        to: 'ending-hidden-fracture',
      },
    ],
    stage: stage(
      '隐藏线起点',
      '片盘与放映窗',
      '多周目的意义，不是重复，而是终于看见之前遗漏了什么。',
      '#1a1d27',
      '#d6defa',
      '#6977a3',
      '/media/hidden/rewind-room.mp4',
      '/media/hidden/rewind-room.webm',
    ),
    isEnding: false,
  },
  'hidden-mirror-stage': {
    id: 'hidden-mirror-stage',
    route: 'hidden',
    act: '回梦线',
    title: '镜台合影',
    subtitle: '这一回不再问你选谁，而是问你愿不愿把每个人都写回去',
    speaker: '旁白',
    location: '镜台舞台',
    time: '梦中',
    mood: '镜子里映出的不是她们的脸，是她们仍然有权做选择的未来。',
    summary: [
      '镜台亮起时，你终于看清之前所有线路背后共同缺的那一块: 不是爱情本身，而是那些被迫交出去的选择权。现在轮到你决定，要不要把这出戏的玩法从“单线通关”改写成“众人归岸”。',
    ],
    choices: [
      {
        id: 'rewrite-the-reels',
        label: '重写片单',
        caption: '要求灵识 3，且至少 2 个明亮结局。',
        to: 'ending-hidden-secret',
        lock: {
          stats: { spirit: 3 },
          radiantEndings: 2,
          reason: '你还没攒够足够的光，来照清整部戏的回环。',
        },
      },
      {
        id: 'burn-the-last-copy',
        label: '烧掉最后一卷片',
        caption: '这样最快结束，也最彻底。',
        to: 'ending-hidden-fracture',
      },
    ],
    stage: stage(
      '隐藏线镜台',
      '水镜与片单',
      '真正的隐藏结局，不是多给一条线，而是让整个结构都开始回应你。',
      '#1d2130',
      '#eef2ff',
      '#7a85b2',
      '/media/hidden/mirror-stage.mp4',
      '/media/hidden/mirror-stage.webm',
    ),
    isEnding: false,
  },
  'ending-hidden-secret': {
    id: 'ending-hidden-secret',
    route: 'hidden',
    act: '隐藏结局',
    title: '众名归岸',
    subtitle: '你终于不只是在一条线上把人带回来了',
    speaker: '旁白',
    location: '放映厅正幕',
    time: '天将明',
    mood: '幕布拉开时，片尾第一次没有遗漏任何名字。',
    summary: [
      '你把四件旧物重新放上片单时，镜台没有崩毁，反而慢慢亮成一整面晨光。那些曾经只能各自收束的命运，第一次被允许并排存在。她们不再只是可攻略对象，而是完整活下来的几种人间可能。',
      '对这个 Demo 来说，这也是一个结构声明: 现在的底层足够承载更复杂的多周目回环、隐藏条件与正式视频接入。',
    ],
    choices: [],
    stage: stage(
      '隐藏真结局',
      '正幕与晨光',
      '当你开始替所有人保留选择，故事才真正开始把你当成主角。',
      '#212532',
      '#f6f8ff',
      '#8b94bc',
      '/media/hidden/ending-secret.mp4',
      '/media/hidden/ending-secret.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-hidden-secret',
      name: '隐藏结局·众名归岸',
      tone: 'secret',
      relic: '回梦片匣',
      summary: '你不再只是在某一条恋爱线上“获胜”，而是开始改写整部戏的结构。',
    },
  },
  'ending-hidden-fracture': {
    id: 'ending-hidden-fracture',
    route: 'hidden',
    act: '隐藏结局',
    title: '空白片尾',
    subtitle: '你让故事结束得很干净，也很冷',
    speaker: '旁白',
    location: '放映间黑场',
    time: '梦醒前',
    mood: '当所有片单都被烧掉，你甚至想不起自己曾想救谁。',
    summary: [
      '最后一卷片在你手里化成灰时，整个放映间迅速暗下去。你醒来时，只记得自己做过一场很长的梦，却再也拼不回任何人的脸。最彻底的坏结局，往往不是失去，而是失去之后你连失去了什么都不知道。',
    ],
    choices: [],
    stage: stage(
      '隐藏坏结局',
      '黑场与冷灰',
      '忘记当然轻，但那不是圆满，只是更彻底的空。',
      '#11131a',
      '#97a0c7',
      '#4e5677',
      '/media/hidden/ending-fracture.mp4',
      '/media/hidden/ending-fracture.webm',
    ),
    isEnding: true,
    ending: {
      id: 'ending-hidden-fracture',
      name: '隐藏结局·空白片尾',
      tone: 'fracture',
      relic: '熄灭片孔',
      summary: '你选择了最轻的退出方式，也把整部戏中最珍贵的回应一并熄灭。',
    },
  },
}

export const endingLibrary = Object.values(storyScenes)
  .filter((scene) => scene.ending)
  .map((scene) => scene.ending!)

export const totalEndingCount = endingLibrary.length
